#############################################################################
# Makefile for building: MolShaCS
# Generated by qmake (2.01a) (Qt 4.8.1) on: sex 31. ago 17:14:59 2012
# Project:  MolShaCS.pro
# Template: app
# Command: c:/QtSDK/QtSources/4.8.1_static/bin/qmake -o Makefile MolShaCS.pro
#############################################################################

first: debug
install: debug-install
uninstall: debug-uninstall
MAKEFILE      = Makefile
QMAKE         = c:/QtSDK/QtSources/4.8.1_static/bin/qmake
DEL_FILE      = rm
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp
COPY_FILE     = $(COPY)
COPY_DIR      = cp -r
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = mv
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		debug \
		release

debug: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_default: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-make_first: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug first
debug-all: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_default: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-make_first: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release first
release-all: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: MolShaCS.pro  ../../../../QtSDK/QtSources/4.8.1_static/mkspecs/default/qmake.conf ../../../../QtSDK/QtSources/4.8.1_static/mkspecs/qconfig.pri \
		../../../../QtSDK/QtSources/4.8.1_static/mkspecs/modules/qt_webkit_version.pri \
		../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/qt_functions.prf \
		../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/qt_config.prf \
		../../../../QtSDK/QtSources/4.8.1_static/mkspecs/win32-g++/qmake.conf \
		../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/exclusive_builds.prf \
		../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/default_pre.prf \
		../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/win32/default_pre.prf \
		../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/debug.prf \
		../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/debug_and_release.prf \
		../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/default_post.prf \
		../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/win32/default_post.prf \
		../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/static.prf \
		../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/win32/rtti.prf \
		../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/win32/exceptions.prf \
		../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/win32/stl.prf \
		../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/warn_on.prf \
		../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/qt.prf \
		../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/win32/thread.prf \
		../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/moc.prf \
		../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/win32/windows.prf \
		../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/resources.prf \
		../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/uic.prf \
		../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/yacc.prf \
		../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/lex.prf \
		../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/include_source_dir.prf \
		c:/QtSDK/QtSources/4.8.1_static/lib/qtmaind.prl \
		c:/QtSDK/QtSources/4.8.1_static/lib/QtGui.prl \
		c:/QtSDK/QtSources/4.8.1_static/lib/QtCore.prl
	$(QMAKE) -o Makefile MolShaCS.pro
../../../../QtSDK/QtSources/4.8.1_static/mkspecs/qconfig.pri:
../../../../QtSDK/QtSources/4.8.1_static/mkspecs/modules/qt_webkit_version.pri:
../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/qt_functions.prf:
../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/qt_config.prf:
../../../../QtSDK/QtSources/4.8.1_static/mkspecs/win32-g++/qmake.conf:
../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/exclusive_builds.prf:
../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/default_pre.prf:
../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/win32/default_pre.prf:
../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/debug.prf:
../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/debug_and_release.prf:
../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/default_post.prf:
../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/win32/default_post.prf:
../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/static.prf:
../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/win32/rtti.prf:
../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/win32/exceptions.prf:
../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/win32/stl.prf:
../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/warn_on.prf:
../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/qt.prf:
../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/win32/thread.prf:
../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/moc.prf:
../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/win32/windows.prf:
../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/resources.prf:
../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/uic.prf:
../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/yacc.prf:
../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/lex.prf:
../../../../QtSDK/QtSources/4.8.1_static/mkspecs/features/include_source_dir.prf:
c:\QtSDK\QtSources\4.8.1_static\lib\qtmaind.prl:
c:\QtSDK\QtSources\4.8.1_static\lib\QtGui.prl:
c:\QtSDK\QtSources\4.8.1_static\lib\QtCore.prl:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile MolShaCS.pro

qmake_all: FORCE

make_default: debug-make_default release-make_default FORCE
make_first: debug-make_first release-make_first FORCE
all: debug-all release-all FORCE
clean: debug-clean release-clean FORCE
distclean: debug-distclean release-distclean FORCE
	-$(DEL_FILE) Makefile

check: first

debug-mocclean: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
