/*
 * Writer.h
 *
 *  Created on: 03/03/2011
 *      Author: Nascimento
 */

#ifndef WRITER_H_
#define WRITER_H_

/*!
 * @brief This class handles all the output provided by the program MolShaCS.
 */

#include "Parser.h"
#include "Mol.h"
#include "Mol2.h"
#include"zlib.h"

/*!
 * This class handles the output generated by the program. Functions are provided to
 * both write computed data to a logfile and show it on the screen.
 */
class Writer {

public:

	//! logfile is defined as a C file to generate a written report (log) of the program run.
	FILE *logfile;
	//! Pointer to a Mol2 object with molecular information
	Mol *Cmol;
	//! gZipped (compacted) ouput file with molecular coordinates after alignment (overlay) in SYBYL MOL2 format.
	gzFile outmol2;

	//! Class constructor. Opens the logfile with the "output" name defined in the input file.
	//! @param Input Pointer to the Parser class.
	Writer(Parser *Input);

	//! This function writes down the parameters given by the user as input.
	//! @param Pointer to the Parser class
	void write_params(Parser *Input);
	//! This function writes a "welcome" message
	void write_welcome(void);
	//! This message shows a char array in the screen and writes it to the logfile.
	//! @param  info char array (82 char long) with a message to be written/shown.
	void write_to_log(char info[82]);
	//! This overloaded function writes a blank line in the logfile and in the screen.
	void write_to_log(void);
	//! Class destructor. Closes the logfile.

	//!
	void write_is_running(void);

	//! This method writes the information "Program is running, please wait".

	/*!
	 * This method writes a PDB file.
	 * @param Cmol Pointer to a PRMTOP object with molecular information
	 * @param xyz C++ vector with new atomic coordinates
	 * @param outname C++ string with output file name
	 */
	void write_pdb(Mol *Cmol, vector<vector<double> >xyz, string outname);

	/*!
	 * This method writes a PDB file.
	 * @param Cmol Pointer to a MOL2 object with molecular information
	 * @param xyz C++ vector with new atomic coordinates
	 * @param outname C++ string with output file name
	 */
	void write_pdb(Mol2 *Cmol2, vector<vector<double> >xyz, string outname);

	/*!
	 * This method writes a MOL2 file.
	 * @param Cmol Pointer to a PRMTOP object with molecular information
	 * @param xyz C++ vector with new atomic coordinates
	 * @param outname C++ string with output file name
	 */
	void writeMol2(Mol2* Cmol, vector<vector<double> >xyz, string outname);
	/*!
	 * This method writes a MOL2 file. Here, the file name will be used from PARSER::output;
	 * @param Cmol Pointer to a PRMTOP object with molecular information
	 * @param xyz C++ vector with new atomic coordinates
	 * @param cc Correlation coefficient to be written in the MOL2 file.
	 */
	void writeMol2(Mol2* Cmol, vector<vector<double> >xyz, double cc);

	/*!
	 * This method closes all the opened files.
	 */
	void close(void);

	/*!
	 * Destructor.
	 */
	~Writer(void);
};

#endif /* WRITER_H_ */
